# basic
title: lelouchcr's blog
subtitle: 
favicon: favicon.ico

# avatar: images/avatar.png 
avatar: https://gravatar.css.network/avatar/f6adb1529491a56dbe31c57d519585f5?s=400&r=g
banner_small: images/banner-small.png
banner_large: images/banner-large.png
# avatar: http://7xrcp8.com1.z0.glb.clouddn.com/avatar.png
# banner_small: http://7xrcp8.com1.z0.glb.clouddn.com/banner-small.png
# banner_large: http://7xrcp8.com1.z0.glb.clouddn.com/banner-large.png

# disqus
disqus_shortname: caorong

# social
social:
  github: https://github.com/caorong
  twitter: https://twitter.com/Lelouchcr
  # weibo: http://weibo.com/cha12chalyc

# nav #
nav:
  home: .
  archive: archives
  # about: about
  rss: atom.xml

# heox-renderre-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false
